definitions:
  routes.PostAuths.AuthEmailInputStruct:
    properties:
      email:
        type: string
    type: object
  routes.PostAuths.AuthEmailOutputStruct:
    properties:
      codeExpiry:
        type: string
    type: object
  routes.RegisterUser.RegisterInputStruct:
    properties:
      code:
        type: string
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
host: <some url>
info:
  contact: {}
  description: API for Polyamanita server functions
  title: Polyamanita API
  version: "1.0"
paths:
  /auths:
    post:
      consumes:
      - application/json
      description: Sends an email to the address passed in with a verification code
        to verify their email
      parameters:
      - description: Email address to send code to
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/routes.PostAuths.AuthEmailInputStruct'
      produces:
      - application/json
      responses:
        "200":
          description: Expiry time of code
          schema:
            $ref: '#/definitions/routes.PostAuths.AuthEmailOutputStruct'
        "500":
          description: Internal Server Error
      summary: Send a Verification Code
      tags:
      - Auth
  /session:
    delete:
      description: Just deletes the cookie the user was using to login
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Logs user out of account
      tags:
      - Auth
  /users:
    post:
      consumes:
      - application/json
      description: Registers the user with input data to DDB
      parameters:
      - description: User Data and code from email
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/routes.RegisterUser.RegisterInputStruct'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "500":
          description: Internal Server Error
      summary: Registers a User
      tags:
      - Users
swagger: "2.0"
