definitions:
  models.Capture:
    properties:
      captureID:
        type: string
      instances:
        items:
          $ref: '#/definitions/models.Instance'
        type: array
      mainSort:
        type: string
      notes:
        type: string
      timesFound:
        type: integer
      userID:
        type: string
    type: object
  models.Instance:
    properties:
      dateFound:
        type: string
      imageLink:
        type: string
      latitude:
        type: number
      location:
        type: string
      longitude:
        type: number
      s3Key:
        type: string
    type: object
  models.User:
    properties:
      TotalCaptures:
        type: integer
      color1:
        type: string
      color2:
        type: string
      email:
        type: string
      follows:
        items:
          type: string
        type: array
      mainSort:
        type: string
      password:
        type: string
      userID:
        type: string
      username:
        type: string
    type: object
  routes.AddCaptures.AddCapturesInputStruct:
    properties:
      captures:
        items:
          properties:
            captureID:
              type: string
            instances:
              items:
                $ref: '#/definitions/models.Instance'
              type: array
            notes:
              type: string
          type: object
        type: array
    type: object
  routes.GetCapture.GetCaptureOutputStruct:
    properties:
      capture:
        $ref: '#/definitions/models.Capture'
    type: object
  routes.GetCapturesList.GetCapturesListOutputStruct:
    properties:
      captures:
        items:
          $ref: '#/definitions/models.Capture'
        type: array
    type: object
  routes.GetUser.GetUserOutputStruct:
    properties:
      user:
        $ref: '#/definitions/models.User'
    type: object
  routes.Login.LoginInputStruct:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  routes.Login.LoginOutputStruct:
    properties:
      accessToken:
        type: string
      userID:
        type: string
    type: object
  routes.PostAuths.AuthEmailInputStruct:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  routes.PostAuths.AuthEmailOutputStruct:
    properties:
      codeExpiry:
        type: string
    type: object
  routes.PostAuthsGen.AuthGenInputStruct:
    properties:
      email:
        type: string
    type: object
  routes.PostAuthsGen.AuthGenOutputStruct:
    properties:
      codeExpiry:
        type: string
    type: object
  routes.RegisterUser.RegisterInputStruct:
    properties:
      code:
        type: string
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  routes.SearchUser.SearchUsersOutputStruct:
    properties:
      users:
        items:
          $ref: '#/definitions/models.User'
        type: array
    type: object
info:
  contact: {}
  description: API for Polyamanita server functions
  title: Polyamanita API
  version: "1.0"
paths:
  /auth:
    post:
      consumes:
      - application/json
      description: Sends an email to the address passed in with a verification code
        to verify their email
      parameters:
      - description: Email address to send code to
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/routes.PostAuths.AuthEmailInputStruct'
      produces:
      - application/json
      responses:
        "200":
          description: Expiry time of code
          schema:
            $ref: '#/definitions/routes.PostAuths.AuthEmailOutputStruct'
        "500":
          description: Internal Server Error
      summary: Send a register Verification Code
      tags:
      - Auth
  /authGen:
    post:
      consumes:
      - application/json
      description: Sends an email to the address passed in with a verification code
        for general use
      parameters:
      - description: Email address to send code to
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/routes.PostAuthsGen.AuthGenInputStruct'
      produces:
      - application/json
      responses:
        "201":
          description: Expiry time of code
          schema:
            $ref: '#/definitions/routes.PostAuthsGen.AuthGenOutputStruct'
        "500":
          description: Internal Server Error
      summary: Send a general Verification Code
      tags:
      - Auth
  /session:
    delete:
      description: Just deletes the cookie the user was using to login
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Logs user out of account
      tags:
      - Auth
    post:
      parameters:
      - description: login credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/routes.Login.LoginInputStruct'
      responses:
        "200":
          description: string username
          schema:
            $ref: '#/definitions/routes.Login.LoginOutputStruct'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Login to an account
      tags:
      - Auth
  /users:
    get:
      consumes:
      - application/json
      description: Searchs for Users with input data from DDB
      parameters:
      - description: username query
        in: query
        name: query
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: String Array of Usernames
          schema:
            $ref: '#/definitions/routes.SearchUser.SearchUsersOutputStruct'
        "500":
          description: Internal Server Error
      summary: Searchs for a User
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: Registers the user with input data to DDB
      parameters:
      - description: User Data and code from email
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/routes.RegisterUser.RegisterInputStruct'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Registers a User
      tags:
      - Users
  /users/{UserID}:
    delete:
      consumes:
      - application/json
      description: Deletes a User with input data from DDB
      parameters:
      - description: the user ID
        in: path
        name: UserID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Deletes a User
      tags:
      - Users
    get:
      consumes:
      - application/json
      description: Gets one user with input data from DDB
      parameters:
      - description: the user ID
        in: path
        name: UserID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: string username
          schema:
            $ref: '#/definitions/routes.GetUser.GetUserOutputStruct'
        "500":
          description: Internal Server Error
      summary: Get a User
      tags:
      - Users
    put:
      consumes:
      - application/json
      description: Updates a User with input data to DDB
      parameters:
      - description: the user ID
        in: path
        name: UserID
        required: true
        type: string
      - description: User data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Updates a User
      tags:
      - Users
  /users/{UserID}/captures:
    get:
      consumes:
      - application/json
      description: Gets a list of captures from a User with input data from DDB
      parameters:
      - description: the user ID
        in: path
        name: UserID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: string username
          schema:
            $ref: '#/definitions/routes.GetCapturesList.GetCapturesListOutputStruct'
        "500":
          description: Internal Server Error
      summary: Gets a list of captures from a User
      tags:
      - Captures
    post:
      consumes:
      - application/json
      description: Gets a list of mushrooms to add as captures to the user journal
      parameters:
      - description: the user ID
        in: path
        name: UserID
        required: true
        type: string
      - description: info to add and update the capture with. Will NOT overwrite notes
          if notes already exist. Instances will append
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/routes.AddCaptures.AddCapturesInputStruct'
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
      summary: Add a new list of captures to the user
      tags:
      - Captures
  /users/{UserID}/captures/{CaptureID}:
    get:
      consumes:
      - application/json
      description: Gets all relevant information about a mushroom that's been captured
        for a user, including image links
      parameters:
      - description: the user ID
        in: path
        name: UserID
        required: true
        type: string
      - description: the capture ID
        in: path
        name: CaptureID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: mushroom information
          schema:
            $ref: '#/definitions/routes.GetCapture.GetCaptureOutputStruct'
        "500":
          description: Internal Server Error
      summary: Get information about a captured mushroom
      tags:
      - Captures
  /users/{UserID}/images:
    post:
      consumes:
      - application/json
      description: USED FOR CAPTURE UPLOAD. MAKE REQUEST HERE TO GET S3 KEY, THEN
        INCLUDE S3KEY IN ADDCAPTURES REQUEST
      parameters:
      - description: number of image upload links / S3 keys to generate. Default is
          1
        in: query
        name: numLinks
        type: number
      - description: the user ID
        in: path
        name: UserID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
      summary: Uploads an image for the user to S3, FOR CAPTURE UPLOAD
      tags:
      - Captures
swagger: "2.0"
