env:
  AWS_S3_ARTIFACTS_BUCKET: polyamanita-artifacts
  AWS_EB_APPLICATION_NAME: polyamanita-server-dev

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
  upload_s3:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Upload to S3
      run: | 
        zip -r ${{vars.GITHUB_SHA}} ./* 

        aws s3 cp ./${{vars.GITHUB_SHA}}.zip s3://${{env.AWS_S3_ARTIFACTS_BUCKET}}/${{vars.GITHUB_SHA}}
        
        aws elasticbeanstalk create-application-version \
          --application-name ${{env.AWS_EB_APPLICATION_NAME}} \
          --version-label ${{vars.GITHUB_SHA}} \
          --source-bundle S3Bucket=${{env.AWS_S3_ARTIFACTS_BUCKET}},S3Key=${{vars.GITHUB_SHA}} \
          --auto-create-application \
          --tags Key=COMMIT_SHA,Value=${{vars.GITHUB_SHA}} \
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
  
  deploy_dev:
    needs: [upload_s3]
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Dev
      run: |
        
      
      
      
